title: Tristan's Blog
description: A cozy retro journal about my thoughts
url: https://your-github-username.github.io
baseurl: ""
theme: jekyll-theme-simple-texture
plugins:
  - jekyll-feed
  - jekyll-seo-tag
