title: Tristan's Blog
description: A cozy retro journal about my thoughts
url: https://your-github-username.github.io
baseurl: ""
remote_theme: yizeng/jekyll-theme-simple-texture
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag

sass:
  style: compressed
  load_paths:
    - assets/css
